### ISSUE TITLE
init-presentation

### ISSUE THREAD

**Issue by Soufiane-Boukhar** [labs-web/lab-heritage#14]
## Travail à faire
- Élaboration d'un presentation sans contenu avec les pages et leurs titres

## Livrable

- docs/* : j'ai modifier tous les fichier dans cette repertoire

- readme.md : ajouter le lien de presentation

- readme.json : ajouter le lien de presentation

**Comment by husseinbouik** [comment]
- le résultat n'est pas conforme au livrables dans la description de l'issue

**Comment by husseinbouik** [comment]
- le pullrequest a une conflit
