### ISSUE TITLE
init-lab

### ISSUE THREAD

**Issue by Soufiane-Boukhar** [labs-web/lab-heritage#7]
## Travail à faire

- Élaboration d'un rapport sans contenu avec les pages et leurs titres

## Livrable
- docs/* : j'ai modifier tous les fichier dans cette repertoire

**Comment by husseinbouik** [comment]
- le résultat n'est pas conforme au livrables dans la description de l'issue

**Comment by essarraj-fouad** [comment]
Le lien du rapport dans le fichier README n'est pas valide

**Comment by husseinbouik** [comment]
- L'issue n'est pas liée avec une pull request ouverte
